source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'
#source 'https://github.com/hk01-digital/hk01-ios-uikit-spec.git'


platform :ios, '9.0'

target 'ActionPickerDemo' do
  use_frameworks!
#pod 'ActionSheetPicker-3.0', :git => 'https://github.com/dd01-sz/ActionSheetPicker-3.0.git'

pod 'ActionSheetPicker-3.0'
end
